//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockBDWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.AudFinances = new HashSet<AudFinance>();
            this.DailyDatas = new HashSet<DailyData>();
            this.EPS_Perf = new HashSet<EPS_Perf>();
            this.Holdings = new HashSet<Holding>();
            this.MF_Perf = new HashSet<MF_Perf>();
            this.News = new HashSet<News>();
        }
    
        public long cID { get; set; }
        public string Ticker { get; set; }
        public string Name { get; set; }
        public Nullable<long> sID { get; set; }
        public decimal AuthCapital { get; set; }
        public decimal PaidupCapital { get; set; }
        public long ShareCount { get; set; }
        public decimal FaceValue { get; set; }
        public long LotSize { get; set; }
        public long ShareType { get; set; }
        public bool ActiveListing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AudFinance> AudFinances { get; set; }
        public virtual ShareType ShareType1 { get; set; }
        public virtual Sector Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyData> DailyDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPS_Perf> EPS_Perf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Holding> Holdings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MF_Perf> MF_Perf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
    }
}
