//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockBDWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPS_Perf
    {
        public long id { get; set; }
        public Nullable<long> cID { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<decimal> Q1 { get; set; }
        public Nullable<decimal> Q2 { get; set; }
        public Nullable<decimal> Half_Yearly { get; set; }
        public Nullable<decimal> Q3 { get; set; }
        public decimal Annual { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
