//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockBDWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holding
    {
        public long id { get; set; }
        public long cID { get; set; }
        public System.DateTime ChangeYear { get; set; }
        public decimal SponDir { get; set; }
        public decimal Gov { get; set; }
        public decimal Inst { get; set; }
        public decimal Forgn { get; set; }
        public decimal Public { get; set; }
        public long ShareCount { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
