//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockBDWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MF_Perf
    {
        public long id { get; set; }
        public Nullable<long> cID { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<long> Quarter { get; set; }
        public decimal NAV_Market { get; set; }
        public decimal NAV_Cost { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
