//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockBDWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recent
    {
        public string Ticker { get; set; }
        public Nullable<decimal> YCP { get; set; }
        public Nullable<decimal> Open { get; set; }
        public Nullable<decimal> LTP { get; set; }
    }
}
